// license-header java merge-point
// Generated by andromda-thymeleaf cartridge (controllers\ControllerImpl.java.vsl)
package bw.co.roguesystems.teseletso.access;

import bw.co.roguesystems.teseletso.SelectItem;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * @see bw.co.roguesystems.teseletso.access.AccessPointController
 */
@Controller
@RequestMapping("/access-point-controller")
public class AccessPointControllerImpl
    extends AccessPointControllerBase
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8595392091732866027L;

    public AccessPointControllerImpl() {
        
        super(
        );
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.AccessPointController#doInitialiseEditScreen(java.lang.Long id, AccessPointVO accessPoint)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form, Model model)
    {
        
        
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.AccessPointController#doDelete(AccessPointVO accessPoint)
     */
    @Override
    public void doDelete(DoDeleteForm form, Model model)
    {
        
        
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.AccessPointController#doSave(AccessPointVO accessPoint)
     */
    @Override
    public void doSave(DoSaveForm form, Model model)
    {
        
        
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.AccessPointController#doInitialiseSearchScreen()
     */
    @Override
    public void doInitialiseSearchScreen(Model model)
    {
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.AccessPointController#doSearch(AccessPointCriteria criteria)
     */
    @Override
    public void doSearch(DoSearchForm form, Model model)
    {
        // populating value with dummy instance
        AccessPointCriteria criteria = new AccessPointCriteria();
        criteria.setType(null);
        criteria.setName(null);
        criteria.setUrl(null);
        criteria.setTypeId(-858803723l);
        form.setCriteria(criteria);
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.AccessPointController#doEdit(java.lang.Long id)
     */
    @Override
    public void doEdit(DoEditForm form, Model model)
    {
    }

    /**
     * This dummy variable is used to populate the "accessPoints" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final AccessPointVO[] accessPoints =
        new AccessPointVO[]
        {
            new AccessPointVO(null, "createdBy-1", "updatedBy-1", LocalDateTime.now(), LocalDateTime.now(), null, "name-1", "url-1", "icon-1"),
            new AccessPointVO(null, "createdBy-2", "updatedBy-2", LocalDateTime.now(), LocalDateTime.now(), null, "name-2", "url-2", "icon-2"),
            new AccessPointVO(null, "createdBy-3", "updatedBy-3", LocalDateTime.now(), LocalDateTime.now(), null, "name-3", "url-3", "icon-3"),
            new AccessPointVO(null, "createdBy-4", "updatedBy-4", LocalDateTime.now(), LocalDateTime.now(), null, "name-4", "url-4", "icon-4"),
            new AccessPointVO(null, "createdBy-5", "updatedBy-5", LocalDateTime.now(), LocalDateTime.now(), null, "name-5", "url-5", "icon-5")
        };
}