// license-header java merge-point
// Generated by andromda-thymeleaf cartridge (controllers\ControllerImpl.java.vsl)
package bw.co.roguesystems.teseletso.access.type;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController
 */
@Controller
@RequestMapping("/access-point-type-controller")
public class AccessPointTypeControllerImpl
    extends AccessPointTypeControllerBase
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2424716228303847710L;

    public AccessPointTypeControllerImpl() {
        
        super(
        );
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController#doInitialiseEditScreen(java.lang.Long id, AccessPointTypeVO accessPointType)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form, Model model)
    {
        // populating value with dummy instance
        AccessPointTypeVO accessPointType = new AccessPointTypeVO();
        accessPointType.setId(3355l);
        accessPointType.setCode(null);
        accessPointType.setName(null);
        accessPointType.setDescription(null);
        form.setAccessPointType(accessPointType);
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController#doDelete(AccessPointTypeVO accessPointType)
     */
    @Override
    public void doDelete(DoDeleteForm form, Model model)
    {
        // populating value with dummy instance
        AccessPointTypeVO accessPointType = new AccessPointTypeVO();
        accessPointType.setId(3355l);
        accessPointType.setCode(null);
        accessPointType.setName(null);
        accessPointType.setDescription(null);
        form.setAccessPointType(accessPointType);
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController#doSave(AccessPointTypeVO accessPointType)
     */
    @Override
    public void doSave(DoSaveForm form, Model model)
    {
        // populating value with dummy instance
        AccessPointTypeVO accessPointType = new AccessPointTypeVO();
        accessPointType.setId(3355l);
        accessPointType.setCode(null);
        accessPointType.setName(null);
        accessPointType.setDescription(null);
        form.setAccessPointType(accessPointType);
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController#doInitialiseSearchScreen()
     */
    @Override
    public void doInitialiseSearchScreen(Model model)
    {
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController#doSearch(java.lang.String criteria)
     */
    @Override
    public void doSearch(DoSearchForm form, Model model)
    {
    }

    /**
     * @see bw.co.roguesystems.teseletso.access.type.AccessPointTypeController#doEdit(java.lang.Long id)
     */
    @Override
    public void doEdit(DoEditForm form, Model model)
    {
    }

    /**
     * This dummy variable is used to populate the "accessPointTypes" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final AccessPointTypeVO[] accessPointTypes =
        new AccessPointTypeVO[]
        {
            new AccessPointTypeVO(null, "code-1", "name-1", "description-1"),
            new AccessPointTypeVO(null, "code-2", "name-2", "description-2"),
            new AccessPointTypeVO(null, "code-3", "name-3", "description-3"),
            new AccessPointTypeVO(null, "code-4", "name-4", "description-4"),
            new AccessPointTypeVO(null, "code-5", "name-5", "description-5")
        };
}